const params = new URLSearchParams(location.search);const id = Number(params.get('id'));
fetch('products.json').then(r=>r.json()).then(list=>{const p = list.find(x=>x.id===id);const root=document.getElementById('product-root');if(!p){root.textContent='Ürün bulunamadı.';return}
 const img = document.createElement('img');img.src = 'data:image/svg+xml;utf8,'+encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='1200' height='800'><rect width='100%' height='100%' fill='#eee'/><text x='50%' y='50%' font-size='48' text-anchor='middle' fill='#222' font-family='Arial' dy='.35em'>${p.name}</text></svg>`);img.style.width='100%';img.style.maxHeight='560px';img.style.objectFit='cover';
 const title = document.createElement('h1');title.textContent=p.name;
 const price = document.createElement('div');price.className='price';price.textContent = p.price.toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
 const desc = document.createElement('p');desc.textContent=p.description;
 const btn = document.createElement('button');btn.textContent='Sepete Ekle';btn.className='btn';btn.style.marginTop='12px';
 btn.addEventListener('click',()=>{const cart = JSON.parse(localStorage.getItem('luxcart-v1')||'[]');const existing = cart.find(i=>i.id===p.id);if(existing){existing.qty+=1}else{cart.push({id:p.id,qty:1,price:p.price,name:p.name})}localStorage.setItem('luxcart-v1',JSON.stringify(cart));alert('Sepete eklendi');document.getElementById('cart-count').textContent = cart.reduce((s,i)=>s+i.qty,0)});
 root.appendChild(img);root.appendChild(title);root.appendChild(price);root.appendChild(desc);root.appendChild(btn);document.getElementById('cart-count').textContent = JSON.parse(localStorage.getItem('luxcart-v1')||'[]').reduce((s,i)=>s+i.qty,0);
}).catch(e=>{document.getElementById('product-root').textContent='Ürün yüklenemedi.'})